### ISSUE TITLE
ImageMagick Error (Resolved)

### ISSUE THREAD

**Issue by bug249286** [Ilyes-El-Majouti/pdftopic#3]
Docker FROM node:16-slim
 
Error Message:
`Ignore the error in ImageMagick.:
convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408.
convert-im6.q16: no images defined `png:-' @ error/convert.c/ConvertImageCommand/3258.`

how to fix.
Thanks.

**Comment by bug249286** [comment]
Resolved
```

# Open the file 
sudo nano /etc/ImageMagick-6/policy.xml

# find and edit the line
<policy domain="coder" rights="none" pattern="PDF" />
# to :
<policy domain="coder" rights="read|write" pattern="PDF" />
```

ref : https://askubuntu.com/questions/1127260/imagemagick-convert-not-allowed

**Comment by Ilyes-El-Majouti** [comment]
Thank you for the report and the solution don't forget to drop a star on the project it will make me happy
