### ISSUE TITLE
how to create all page to 1 picture

### ISSUE THREAD

**Issue by bug249286** [Ilyes-El-Majouti/pdftopic#4]
how to convert all page to 1 picture
thanks.

**Comment by Ilyes-El-Majouti** [comment]
My package does not allow to convert all the pages of the pdf into an image but I can implement an update to be able to do it.

**Comment by Ilyes-El-Majouti** [comment]
I will update you as soon as possible
Thanks to you.

**Comment by Ilyes-El-Majouti** [comment]
No sorry I'm overwhelmed at the moment I'll do it to you at the end of the week

**Comment by bug249286** [comment]
Thank you very much for your kindness

**Comment by Ilyes-El-Majouti** [comment]
The new version is now available and I hope you enjoy it.
